namespace Ago.Calendar.Domain;

/// <summary>
/// `adr/0184`: the calendar's thin operational record about a person - <b>not</b> a lead card, not a
/// person store, and deliberately not a copy of anything chat holds. Chat owns the Person (display
/// name, contact channels, operator notes, any advisory attribute); this row exists only because
/// CLAUDE.md rule 8 forbids a booking write from reading a remote service, and two facts the booking
/// write gates on are generated by this product itself: whether the phone this person books with
/// has been proven reachable (`20-09`), and how many times they failed to turn up (`20-04`).
///
/// <para><b>Keyed by the opaque person id, never by phone.</b> The id is chat's own visitor id for a
/// chat-origin booking, or one this product minted locally for a booking with no chat origin
/// (`adr/0184` decision 2) - either way a bare <see cref="Guid"/>, because the person is owned by
/// chat and wrapping the id in an <c>Ago.Calendar</c> id type would falsely claim ownership this
/// decision moves out of the calendar (<see cref="Event.PersonId"/>'s own remarks). Two people who
/// happen to share a phone number are two rows, exactly as `adr/0147` decided ("a phone is a hint,
/// not proof"); nothing here ever merges them.</para>
///
/// <para><b>The phone is kept (author decision O1) as an operational value, not as identity.</b>
/// <see cref="PhoneVerifiedAt"/> is a statement about <em>this</em> number, so the number it was
/// proven for has to sit beside it; the per-phone booking rate limit reads it too. Chat still owns
/// the canonical channel list - a person's phone on this row is the one they last booked with, and
/// the calendar never serves it as "the person's contact channels".</para>
///
/// <para><b>Personal data.</b> A phone number keyed by a person id is personal data and is recorded
/// as such in <c>ago-root/docs/architecture/personal-data.md</c>; the display name and free-text
/// notes the old <c>customers</c> row used to hold are gone from this product entirely.</para>
/// </summary>
public sealed class PersonRecord
{
    public Guid PersonId { get; }

    public TenantId TenantId { get; }

    public PhoneNumber Phone { get; private set; }

    /// <summary>How many times this person failed to turn up. A count rather than a flag: the
    /// product spec names "prepayment required for customers with a no-show history" as the future
    /// rule this feeds, and one strike is not the same thing as five. Written by whoever marks an
    /// <see cref="Event"/> as <see cref="EventStatus.NoShow"/> (`20-04`).</summary>
    public int NoShowCount { get; private set; }

    public DateTimeOffset FirstSeenAt { get; }

    public DateTimeOffset LastSeenAt { get; private set; }

    /// <summary>
    /// `20-09`: when <see cref="Phone"/> was first proven reachable by whoever books with it, or
    /// <see langword="null"/> if it never has been. This aggregate's own C# writers -
    /// <see cref="Register"/> and <see cref="RecordVerifiedPhone"/> - are the precondition's canonical
    /// statement; the real, load-bearing write is <c>Ago.Calendar.Infrastructure.Postgres.BookingStore</c>'s
    /// own raw SQL upsert (that type's own remarks), the identical "the domain method states the rule,
    /// the SQL is what runs" split <see cref="Event.Claim"/> already has with <c>ClaimSlotSql</c>.
    /// </summary>
    public DateTimeOffset? PhoneVerifiedAt { get; private set; }

    /// <summary>
    /// `23-12`/`decisions.md` §5: "I called and it is them" - a different fact from
    /// <see cref="PhoneVerifiedAt"/>'s own SMS-code answer, recorded separately rather than folded
    /// into it, and only ever set by an operator who could see the number to call it
    /// (<c>ConfirmOperatorVerifiedPhoneHandler</c>'s own <c>Permission.CustomerRead</c> gate).
    /// Earliest-wins and idempotent, the identical shape <see cref="RecordVerifiedPhone"/> uses.
    /// </summary>
    public DateTimeOffset? PhoneConfirmedByOperatorAt { get; private set; }

    private PersonRecord(Guid personId, TenantId tenantId, PhoneNumber phone, DateTimeOffset now)
    {
        PersonId = personId;
        TenantId = tenantId;
        Phone = phone;
        FirstSeenAt = now;
        LastSeenAt = now;
    }

    // EF Core materialization only - never called by domain code.
    private PersonRecord()
    {
    }

    public static PersonRecord Register(Guid personId, TenantId tenantId, PhoneNumber phone, DateTimeOffset now)
    {
        if (personId == Guid.Empty)
        {
            throw new ArgumentException("A person record needs a real person id.", nameof(personId));
        }

        return new PersonRecord(personId, tenantId, phone, now);
    }

    /// <summary>`20-09`: the domain's own canonical statement of "once verified, stays verified" -
    /// idempotent and earliest-wins, the identical rule <c>BookingStore</c>'s own SQL <c>COALESCE</c>
    /// applies at the row level.</summary>
    public void RecordVerifiedPhone(DateTimeOffset verifiedAt) => PhoneVerifiedAt ??= verifiedAt;

    /// <summary>`23-12`: "once an operator has confirmed it by calling, that stands" - see
    /// <see cref="PhoneConfirmedByOperatorAt"/>'s own remarks for why this is a distinct fact from
    /// <see cref="RecordVerifiedPhone"/> rather than a second caller of it.</summary>
    public void RecordOperatorConfirmedPhone(DateTimeOffset confirmedAt) => PhoneConfirmedByOperatorAt ??= confirmedAt;

    public void RecordNoShow(DateTimeOffset now)
    {
        NoShowCount++;
        Touch(now);
    }

    /// <summary>
    /// A later booking from the same person with a different number. The verification facts belong
    /// to the number they were established for, so changing the number clears them - a person who
    /// verified one phone has not thereby verified the next one. Same number: nothing changes, and
    /// the earliest-wins rule on the two timestamps is untouched.
    /// </summary>
    public void ChangePhone(PhoneNumber phone)
    {
        if (phone == Phone)
        {
            return;
        }

        Phone = phone;
        PhoneVerifiedAt = null;
        PhoneConfirmedByOperatorAt = null;
    }

    /// <summary>Moves the "last seen" watermark forward and never backward - a late-arriving write
    /// must not rewind it, and time is a parameter here precisely so that rule is testable.</summary>
    public void Touch(DateTimeOffset now)
    {
        if (now > LastSeenAt)
        {
            LastSeenAt = now;
        }
    }
}
