// <auto-generated />
using System;
using System.Collections.Generic;
using Ago.Calendar.Infrastructure.Postgres.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ago.Calendar.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AgoCalendarDbContext))]
    [Migration("20260903193753_Stage22RemoveOperatorIdentityAddRoleAssignmentProjections")]
    partial class Stage22RemoveOperatorIdentityAddRoleAssignmentProjections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ago.Calendar.Domain.BookingCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_calendars_published")
                        .HasFilter("is_published");

                    b.ToTable("calendars", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.CalendarMembership", b =>
                {
                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("CalendarId", "WorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("calendar_workers", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.ChatBookingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("TenantId");

                    b.ToTable("chat_booking_tasks", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.ChatModuleRegistration", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Credential")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("credential");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("registered_at");

                    b.HasKey("TenantId");

                    b.ToTable("chat_module_registrations", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("integer")
                        .HasColumnName("no_show_count");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("phone_verified_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Phone")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_tenant_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<DateTimeOffset?>("ConfirmationDeadline")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmation_deadline");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ends_at");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_events_booking_id")
                        .HasFilter("booking_id IS NOT NULL");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("CalendarId", "StartsAt")
                        .HasDatabaseName("ix_events_available")
                        .HasFilter("status = 'Available'");

                    b.HasIndex("TenantId", "ConfirmationDeadline")
                        .HasDatabaseName("ix_events_pending_confirmation")
                        .HasFilter("status = 'PendingConfirmation'");

                    b.HasIndex("CalendarId", "WorkerId", "LocalDate")
                        .HasDatabaseName("ix_events_worker_day");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.PendingPhoneVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("delivery_method");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("ProofExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("proof_expires_at");

                    b.Property<byte[]>("ProofTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("proof_token_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("pending_phone_verifications", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.ServiceOffering", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("WorkerId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("worker_services", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("public_key");

                    b.Property<string[]>("_allowedOrigins")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_origins");

                    b.HasKey("Id");

                    b.HasIndex("PublicKey")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_public_key");

                    b.HasIndex("_allowedOrigins")
                        .HasDatabaseName("ix_tenants_allowed_origins");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_allowedOrigins"), "gin");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("DisplayNameIsCustom")
                        .HasColumnType("boolean")
                        .HasColumnName("display_name_is_custom");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.WorkerSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("buffer_minutes");

                    b.Property<bool>("BuffersCountTowardServiceDuration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("buffers_count_toward_service_duration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("CycleAnchor")
                        .HasColumnType("date")
                        .HasColumnName("cycle_anchor");

                    b.Property<TimeOnly?>("CycleEndsAt")
                        .HasColumnType("time")
                        .HasColumnName("cycle_ends_at");

                    b.Property<int?>("CycleRestDays")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_rest_days");

                    b.Property<TimeOnly?>("CycleStartsAt")
                        .HasColumnType("time")
                        .HasColumnName("cycle_starts_at");

                    b.Property<int?>("CycleWorkingDays")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_working_days");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("horizon_days");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateOnly>("MaterializeFrom")
                        .HasColumnType("date")
                        .HasColumnName("materialize_from");

                    b.Property<int>("SlotMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("slot_minutes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId")
                        .IsUnique()
                        .HasDatabaseName("ux_worker_schedules_worker_id");

                    b.ToTable("worker_schedules", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.WorkingHoursRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndsAt")
                        .HasColumnType("time")
                        .HasColumnName("ends_at");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.HasIndex("CalendarId", "WorkerId")
                        .HasDatabaseName("ix_working_hours_rules_calendar_worker");

                    b.ToTable("working_hours_rules", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Infrastructure.Postgres.Persistence.RoleAssignmentProjectionRecord", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_subject_id");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("OperatorId", "TenantId");

                    b.ToTable("role_assignment_projections", (string)null);
                });

            modelBuilder.Entity("Ago.Platform.Persistence.Postgres.InboxRecord", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Consumer")
                        .HasColumnType("text")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("Ago.Platform.Persistence.Postgres.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partition_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("TraceContext")
                        .HasColumnType("text")
                        .HasColumnName("trace_context");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Ago.Calendar.Domain.BookingCalendar", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.CalendarMembership", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.BookingCalendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Calendar.Domain.Worker", null)
                        .WithMany("_calendars")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.ChatBookingTask", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.BookingCalendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Calendar.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.ChatModuleRegistration", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.Tenant", null)
                        .WithOne()
                        .HasForeignKey("Ago.Calendar.Domain.ChatModuleRegistration", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Customer", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Event", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ago.Calendar.Domain.BookingCalendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Calendar.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Ago.Calendar.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.HasOne("Ago.Calendar.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Calendar.Domain.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.PendingPhoneVerification", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Service", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.ServiceOffering", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Calendar.Domain.Worker", null)
                        .WithMany("_services")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Worker", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.WorkerSchedule", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.WorkingHoursRule", b =>
                {
                    b.HasOne("Ago.Calendar.Domain.BookingCalendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ago.Calendar.Domain.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ago.Calendar.Domain.Worker", b =>
                {
                    b.Navigation("_calendars");

                    b.Navigation("_services");
                });
#pragma warning restore 612, 618
        }
    }
}
