using System.Collections.Concurrent;
using Ago.Calendar.Application.Abstractions;
using Microsoft.Extensions.Logging;

namespace Ago.Calendar.Module.PhoneVerification;

/// <summary>
/// `20-10`: <c>Ago.Calendar.Module</c> registers this as <see cref="IPhoneVerificationSender"/>
/// unconditionally - the item's own Done-when: "confirm <c>FakePhoneVerificationSender</c> is the only
/// sender registered." A deliberate, different choice from `ago-chat`'s own
/// <c>UnconfiguredPhoneVerificationSender</c> (`14-15`), which throws.
///
/// <para><b>What this fakes, stated precisely.</b> It fakes exactly one real-world side effect: no SMS
/// or voice call is actually placed. Everything upstream of this call is real - the code is genuinely
/// generated by a CSPRNG, genuinely hashed, genuinely stored, and genuinely checked by
/// <see cref="Domain.PendingPhoneVerification.AttemptConfirm"/>'s own constant-time comparison. This
/// type's only job is to make the real code visible somewhere a person or a test can read it, in place
/// of a paid call to an account this deployment does not have.</para>
///
/// <para><b>Why unconditional, not <c>UnconfiguredPhoneVerificationSender</c>-shaped.</b> That type
/// throws because `14-15`'s own scope never needed a working end-to-end demo before a vendor was chosen
/// - the honest gap was named and left open. This item's whole point is the opposite: a real, live,
/// first-time visitor completing a real booking through the public widget, which a sender that refuses
/// every call could never demonstrate. A sender that always succeeds, minus the one side effect this
/// deployment cannot afford, is what makes that possible.</para>
///
/// <para><b>Where the code surfaces.</b> A structured log line at <c>Information</c>, with a
/// greppable, unambiguous tag - the floor this item's own backlog file names as sufficient for the
/// automated Done-when tests (which register their own spy <see cref="IPhoneVerificationSender"/> via
/// <c>ConfigureTestServices</c> rather than parsing logs) and enough for a human to <c>kubectl logs</c>
/// it on the demo cluster by hand. <see cref="TryGetLastCode"/> additionally keeps the most recent code
/// per phone number in memory, cheaply, so <c>PhoneVerificationDevEndpoints</c> can offer the same value
/// over HTTP for a person clicking through the flow - see that file's own remarks for why this is
/// genuinely cheap rather than gold-plating, and why it is not a substitute for the log line (single
/// process, lost on restart, never a system of record).</para>
/// </summary>
public sealed class FakePhoneVerificationSender(ILogger<FakePhoneVerificationSender> logger) : IPhoneVerificationSender
{
    private readonly ConcurrentDictionary<string, string> _lastCodeByPhone = new();

    public Task SendCodeAsync(PhoneVerificationDelivery delivery, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(delivery);

        _lastCodeByPhone[delivery.Phone] = delivery.Code;

        logger.LogInformation(
            "Phone verification code for {Phone}: {Code} (FakePhoneVerificationSender - no real SMS was sent)",
            delivery.Phone, delivery.Code);

        return Task.CompletedTask;
    }

    /// <summary>Dev/demo convenience only - see this type's own remarks. Not part of
    /// <see cref="IPhoneVerificationSender"/>: nothing in <c>Application</c> may depend on a fake sender
    /// exposing more than the port promises, so this is resolved by its concrete type, from
    /// <c>Ago.Calendar.Api</c>'s own dev-only endpoint alone.</summary>
    public bool TryGetLastCode(string phone, out string code) => _lastCodeByPhone.TryGetValue(phone, out code!);
}
